### ISSUE TITLE
add support for plotting equipotential lines

### ISSUE THREAD

**Issue by CD3** [CD3/VectorFieldPlot#1]

**Comment by Geek3wiki** [comment]
Equipotential lines have been implenented since version 2.3 of VectorFieldPlot. See the function doc.draw_contours() on https://commons.wikimedia.org/wiki/User:Geek3/VectorFieldPlot#Drawing_content_to_the_image_document . An example image is https://commons.wikimedia.org/wiki/File:VFPt_metal_balls_largesmall_potential%2Bcontour.svg

**Comment by CD3** [comment]
Thanks for the info. It looks like you are actively developing and have added several features since I created this fork. I haven't worked on this in many years, but I use it ever semester in my Physics II class. I will look to see if I can just start using your version and delete this repository.
