### ISSUE TITLE
identifying messages and errors by priority

### ISSUE THREAD

**Issue by bcrowell** [CD3/VectorFieldPlot#5]
I tried to do a second pull request for this change, but it seems that the github interface doesn't want to allow me to do a second one when there is a first one outstanding. The diff is here:

https://github.com/bcrowell/VectorFieldPlot/commit/60f6db475e25c6cd519fc9921891d179e8e737da

**Comment by CD3** [comment]
I think if you push your updates to the branch that you submitted the pull request for it will automatically update the pull request.

I would prefer to use Python's standard library `logging` module for this so that the user can set the logging level. The `message` function you added is hard-coded to only print messages that have a priority greater than or equal to 2, so any messages printed with priority 1 are effectively removed.

**Comment by bcrowell** [comment]
Thanks for the speedy response and the help understanding how pull requests work. I've changed the code to handle logging using the standard logging module, and have added some documentation to the end of the README on how to set the logging level.

**Comment by CD3** [comment]
Great. Thanks. I'll merge your commits.
